function getBrandColor(){return fsGet(FS_KEYS.style,{accent:"#f4c400"}).accent||"#f4c400"}
const invoiceTemplates=['studio','editorial','compact','soft','frame','accent'];
const appearanceDefaults={template:"studio",showLogo:true,showVat:true,showPayment:true,showNote:true,showClientEmail:true,showClientAddress:true,showCompanyPhone:true,showCompanyEmail:true,showCompanyWeb:true,showCompanyId:true,showCompanyAddress:true,showPageNumbers:true,footerText:"",labels:{invoice:"FAKTURA",issuer:"IZDAVALAC",client:"RAČUN ZA",items:"Opis stavke",quantity:"Količina",price:"Cijena",total:"Ukupno"}};
function getAppearance(){const appearance={...appearanceDefaults,...fsGet('fs7_invoice_appearance',{})};if(!invoiceTemplates.includes(appearance.template))appearance.template='studio';return appearance}
function renderAppearance(){
 const c=getCompany(),s=fsGet(FS_KEYS.style,{accent:"#f4c400"}),a=getAppearance(),bc=s.accent;
 $("viewContainer").innerHTML=`<div class="page appearance-page">
  <div class="page-heading"><div><h1>Izgled fakture</h1><p class="page-subtitle">Prilagodite A4 dokument. Promjene utiču na nove i postojeće fakture koje se ponovo generišu.</p></div><div class="page-actions"><button class="btn light" onclick="resetAppearanceSettings()">Vrati zadane postavke</button><button class="btn accent" onclick="saveAppearanceSettings()">Sačuvaj izgled</button></div></div>
  <div class="appearance-layout v13-appearance">
   <div class="appearance-controls">
    <div class="card settings-card"><div class="settings-card-title"><div><h2>Osnovni izgled</h2><p>Faktura je uvijek čista i poslovna; brand boja se koristi samo na dokumentu.</p></div></div>
      <div class="field"><label>Šablon dokumenta</label><div class="template-picker" id="templatePicker">
       ${[['studio','Studio','Zaobljeni dokument i prozračna tabela'],['editorial','Editorial','Dijagonalne plohe i elegantna tipografija'],['compact','Compact','Kompaktan raspored i više stavki po stranici'],['soft','Soft','Zaobljene stavke i naglašeno podnožje'],['frame','Frame','Kartice, okvir i jasno odvojeni podaci'],['accent','Accent','Obojeno zaglavlje tabele i čisto podnožje']].map(x=>`<button class="template-choice ${a.template===x[0]?'active':''}" data-template="${x[0]}"><span class="template-mini ${x[0]}"></span><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}
       <button class="template-choice custom-template-choice" type="button" onclick="openCustomDesignInfo()"><span class="template-mini custom"><b>＋</b></span><strong>Custom dizajn</strong><small>Dizajn fakture izrađen po vašoj želji</small></button>
      </div></div>
      <div class="field brand-field"><label>Glavna boja dokumenta</label><div class="brand-picker"><input id="brandColor" type="color" value="${bc}"><div><input id="brandHexInput" class="appearance-hex-input" value="${bc.toUpperCase()}" maxlength="7" aria-label="HEX boja"><span>Tabela, ukupno i akcenti</span></div></div></div>
      <div class="field"><label>Logo</label><label class="brand-file-picker" for="brandLogo"><span><strong id="brandLogoName">Odaberi logo</strong><small>PNG, JPG ili WEBP · čuva se lokalno</small></span><span class="btn light small">Odaberi fajl</span></label><input id="brandLogo" type="file" accept="image/*" style="display:none"><div class="field-hint">Logo se prikazuje u zaglavlju A4 dokumenta.</div></div>
    </div>
    <div class="card settings-card"><div class="settings-card-title"><div><h2>Sadržaj dokumenta</h2><p>Odaberite koje informacije treba prikazati u finalnoj fakturi.</p></div></div>
      <div class="appearance-toggles">
       ${[['showLogo','Prikaži logo','Logo firme u zaglavlju'],['showVat','Prikaži PDV','PDV po stavci i u sažetku'],['showPayment','Prikaži način plaćanja','Način plaćanja u podnožju'],['showNote','Prikaži napomenu','Napomena / uslovi plaćanja'],['showClientEmail','Prikaži email klijenta','Email u bloku klijenta'],['showClientAddress','Prikaži adresu klijenta','Adresa i grad klijenta'],['showCompanyPhone','Prikaži telefon firme','Telefon u podacima firme'],['showCompanyEmail','Prikaži email firme','Email u podacima firme'],['showCompanyWeb','Prikaži web firme','Web stranica u podacima firme'],['showCompanyId','Prikaži ID/PDV firme','Identifikacioni podaci firme'],['showCompanyAddress','Prikaži adresu firme','Adresa izdavaoca'],['showPageNumbers','Prikaži brojeve stranica','Na višestraničnim fakturama']].map(x=>`<label class="appearance-toggle"><span><strong>${x[1]}</strong><small>${x[2]}</small></span><input type="checkbox" id="${x[0]}" ${a[x[0]]!==false?'checked':''}><i></i></label>`).join('')}
      </div>
      <div class="field"><label>Tekst u footeru</label><input id="appearanceFooterText" value="${esc(a.footerText||'')}" maxlength="180" placeholder="Kratka poruka ili uslovi plaćanja"></div><div class="form-grid two appearance-label-grid"><label class="field"><span>Oznaka dokumenta</span><input id="appearanceLabelInvoice" value="${esc(a.labels?.invoice||'FAKTURA')}"></label><label class="field"><span>Oznaka izdavaoca</span><input id="appearanceLabelIssuer" value="${esc(a.labels?.issuer||'IZDAVALAC')}"></label><label class="field"><span>Oznaka klijenta</span><input id="appearanceLabelClient" value="${esc(a.labels?.client||'RAČUN ZA')}"></label><label class="field"><span>Oznaka stavke</span><input id="appearanceLabelItems" value="${esc(a.labels?.items||'Opis stavke')}"></label></div>
    </div>
    <div class="card settings-card sample-data-card"><div class="settings-card-title"><div><h2>Pregled sa primjerom</h2><p>Podaci ispod su namjerno popunjeni da odmah vidite kompletan izgled dokumenta.</p></div></div><div class="sample-data"><span><b>Nordvale Services</b> · Usluga održavanja poslovnog prostora</span><span><b>Klijent:</b> Bluehaven Trade LLC · Sarajevo</span><span><b>Iznos:</b> 1.500,00 KM · PDV 17%</span></div></div>
   </div>
   <div class="appearance-preview-wrap"><div class="preview-head"><div><h2>A4 dokument</h2><p class="page-subtitle">Live preview · primjer fakture</p></div><span class="preview-scale">100%</span></div><div class="preview-shell appearance-a4-shell"><div id="brandPreview"></div></div></div>
  </div>
 </div>`;
 $("templatePicker").querySelectorAll('.template-choice[data-template]').forEach(b=>b.onclick=()=>{ $("templatePicker").querySelectorAll('.template-choice[data-template]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderBrandPreview() });
 $("brandColor").oninput=()=>{$("brandHexInput").value=$("brandColor").value.toUpperCase();renderBrandPreview()};
 $("brandHexInput").oninput=()=>{const value=$("brandHexInput").value.trim();if(/^#[0-9a-f]{6}$/i.test(value)){$("brandColor").value=value;renderBrandPreview()}};
 $("brandLogo").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{saveCompany({...getCompany(),logo:r.result});if($("brandLogoName"))$("brandLogoName").textContent=f.name;renderBrandPreview()};r.readAsDataURL(f)};
 ['showLogo','showVat','showPayment','showNote','showClientEmail','showClientAddress','showCompanyPhone','showCompanyEmail','showCompanyWeb','showCompanyId','showCompanyAddress','showPageNumbers','appearanceFooterText','appearanceLabelInvoice','appearanceLabelIssuer','appearanceLabelClient','appearanceLabelItems'].forEach(id=>$(id).onchange=renderBrandPreview);
 renderBrandPreview();
}
function sampleAppearanceData(){return {company:'Nordvale Services d.o.o.',address:'Ulica Kralja Tvrtka 18',city:'Sarajevo',email:'office@nordvale.example',phone:'+387 61 234 567',client:'Bluehaven Trade LLC',clientAddress:'Maršala Tita 42',clientCity:'Sarajevo',clientEmail:'finance@bluehaven.example',number:'001/2026',date:'21.09.2026',due:'05.10.2026',items:[['Mjesečno održavanje poslovnog prostora',1,1282.05],['Dodatna usluga čišćenja',1,0]],subtotal:1282.05,vat:217.95,total:1500}}
function renderBrandPreview(){const root=$("brandPreview");if(!root)return;const saved=getAppearance();const a={...saved,showLogo:$("showLogo")?.checked??saved.showLogo,showVat:$("showVat")?.checked??saved.showVat,showPayment:$("showPayment")?.checked??saved.showPayment,showNote:$("showNote")?.checked??saved.showNote,showClientEmail:$("showClientEmail")?.checked??saved.showClientEmail,showClientAddress:$("showClientAddress")?.checked??saved.showClientAddress,showCompanyPhone:$("showCompanyPhone")?.checked??saved.showCompanyPhone,showCompanyEmail:$("showCompanyEmail")?.checked??saved.showCompanyEmail,showCompanyWeb:$("showCompanyWeb")?.checked??saved.showCompanyWeb,showCompanyId:$("showCompanyId")?.checked??saved.showCompanyId,showCompanyAddress:$("showCompanyAddress")?.checked??saved.showCompanyAddress,footerText:$("appearanceFooterText")?.value??saved.footerText,labels:{...saved.labels,invoice:$("appearanceLabelInvoice")?.value||saved.labels?.invoice,issuer:$("appearanceLabelIssuer")?.value||saved.labels?.issuer,client:$("appearanceLabelClient")?.value||saved.labels?.client,items:$("appearanceLabelItems")?.value||saved.labels?.items}};const template=document.querySelector('.template-choice.active')?.dataset.template||saved.template;const c=getCompany(),bc=$("brandColor")?.value||getBrandColor(),d=sampleAppearanceData();const logo=d.company;
 const logoHtml=a.showLogo!==false?(c.logo?`<img src="${c.logo}" alt="Logo">`:`<div class="sample-logo-mark" style="background:${bc};${contrastText(bc)}">F</div><strong>${esc(logo)}</strong>`):`<strong>${esc(logo)}</strong>`;
 root.innerHTML=`<div class="sample-a4 template-${template}">
  <div class="sample-top"><div class="sample-brand">${logoHtml}<span>${a.showCompanyAddress?`${esc(d.address)} · ${esc(d.city)}`:''}${a.showCompanyEmail?` · ${esc(d.email)}`:''}</span></div><div class="sample-title"><strong>${esc(a.labels.invoice)}</strong><b>${d.number}</b><span>Izdano ${d.date}</span><span>Rok plaćanja ${d.due}</span></div></div>
  <div class="sample-parties"><div><small>${esc(a.labels.issuer)}</small><strong>${esc(d.company)}</strong>${a.showCompanyAddress?`<span>${esc(d.address)}</span><span>${esc(d.city)}</span>`:''}${a.showCompanyEmail?`<span>${esc(d.email)}</span>`:''}${a.showCompanyPhone?`<span>${esc(d.phone)}</span>`:''}${a.showCompanyId?'<span>ID/PDV: 420000000000</span>':''}</div><div><small>${esc(a.labels.client)}</small><strong>${esc(d.client)}</strong>${a.showClientAddress?`<span>${esc(d.clientAddress)}</span><span>${esc(d.clientCity)}</span>`:''}${a.showClientEmail?`<span>${esc(d.clientEmail)}</span>`:''}</div></div>
  <table><thead><tr style="background:${bc};${contrastText(bc)}"><th>${esc(a.labels.items)}</th><th>Količina</th><th>Cijena</th>${a.showVat?'<th>PDV</th>':''}<th>Ukupno</th></tr></thead><tbody><tr><td><strong>${esc(d.items[0][0])}</strong><small>Mjesečna usluga</small></td><td>1</td><td>${money(d.items[0][2], 'KM')}</td>${a.showVat?'<td>17%</td>':''}<td>${money(d.items[0][2], 'KM')}</td></tr><tr><td>${esc(d.items[1][0])}</td><td>1</td><td>0,00 KM</td>${a.showVat?'<td>17%</td>':''}<td>0,00 KM</td></tr></tbody></table>
  <div class="sample-summary"><div class="summary-lines"><span><em>Međuzbir</em><b>1.282,05 KM</b></span>${a.showVat?'<span><em>PDV 17%</em><b>217,95 KM</b></span>':''}</div><div class="sample-total" style="background:${bc};${contrastText(bc)}"><span>UKUPNO</span><strong>1.500,00 KM</strong></div></div>
  <div class="sample-bottom"><div><small>NAČIN PLAĆANJA</small><span>${a.showPayment?'Bankovni transfer':'—'}</span>${a.showNote?`<p>Hvala na povjerenju. Molimo da uplatu izvršite do navedenog roka.</p>`:''}</div><div><small>PODACI FIRME</small>${a.showCompanyPhone?`<span>${esc(d.phone)}</span>`:''}${a.showCompanyEmail?`<span>${esc(d.email)}</span>`:''}${a.showCompanyWeb?'<span>Fakture · woxdzn.com</span>':''}${a.showCompanyId?'<span>ID/PDV: 420000000000</span>':''}${a.footerText?`<p>${esc(a.footerText)}</p>`:''}</div></div>
 </div>`
}
function saveAppearanceSettings(){const s=fsGet(FS_KEYS.style,{accent:'#f4c400'}),labels={invoice:$("appearanceLabelInvoice").value.trim()||'FAKTURA',issuer:$("appearanceLabelIssuer").value.trim()||'IZDAVALAC',client:$("appearanceLabelClient").value.trim()||'RAČUN ZA',items:$("appearanceLabelItems").value.trim()||'Opis stavke'};const a={template:document.querySelector('.template-choice.active')?.dataset.template||'studio',showLogo:$("showLogo").checked,showVat:$("showVat").checked,showPayment:$("showPayment").checked,showNote:$("showNote").checked,showClientEmail:$("showClientEmail").checked,showClientAddress:$("showClientAddress").checked,showCompanyPhone:$("showCompanyPhone").checked,showCompanyEmail:$("showCompanyEmail").checked,showCompanyWeb:$("showCompanyWeb").checked,showCompanyId:$("showCompanyId").checked,showCompanyAddress:$("showCompanyAddress").checked,showPageNumbers:$("showPageNumbers").checked,footerText:$("appearanceFooterText").value.trim(),labels};const color=$("brandHexInput").value.trim();if(!/^#[0-9a-f]{6}$/i.test(color)){toast('Unesite ispravnu HEX boju, npr. #D71920.');return}fsSet(FS_KEYS.style,{...s,accent:color});fsSet('fs7_invoice_appearance',a);applyAppearance?.();renderBrandPreview();toast('Izgled fakture je sačuvan.')}
function resetAppearanceSettings(){confirmAction('Vrati zadane postavke izgleda?',()=>{fsSet(FS_KEYS.style,{...fsGet(FS_KEYS.style,{accent:'#f4c400'}),accent:'#f4c400'});fsSet('fs7_invoice_appearance',appearanceDefaults);renderAppearance();toast('Zadane postavke izgleda su vraćene.')})}
function openCustomDesignInfo(){openModal('Custom dizajn fakture',`<div class="custom-design-info"><div class="custom-design-icon">✦</div><div><strong>Dizajn prilagođen vašem poslovanju</strong><p>Custom dizajni izrađuju se posebno prema vizuelnom identitetu, sadržaju i zahtjevima vaše firme te se dodatno naplaćuju.</p><p>Za ponudu i dogovor javite se na <a href="mailto:hello@woxdzn.com">hello@woxdzn.com</a>.</p></div></div>`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Zatvori</button><button class="btn accent" onclick="requestCustomDesign()">Pošalji upit</button></div>`)}
function requestCustomDesign(){closeModal();window.location.href='mailto:hello@woxdzn.com?subject=Upit%20za%20custom%20dizajn%20fakture'}
function contrastText(hex){const h=hex.replace('#','');if(h.length!==6)return'color:#111';const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16),lum=(r*299+g*587+b*114)/1000;return lum<150?'color:#fff':'color:#111'}

/* Keep the preview's CSS accent in sync with the unsaved picker value. */
const renderBrandPreviewWithLiveAccent=renderBrandPreview;
renderBrandPreview=function(){renderBrandPreviewWithLiveAccent();const root=$('brandPreview'),color=$('brandColor')?.value;if(root&&color)root.style.setProperty('--brand-doc',color)};
