const sectionHandlers={
  firma:[()=>getCompany(),value=>saveCompany(value)],postavke:[()=>getSettings(),value=>saveSettings(value)],klijenti:[()=>getClients(),value=>saveClients(value)],fakture:[()=>getInvoices(),value=>saveInvoices(value)],ponude:[()=>getOffers(),value=>saveOffers(value)],katalog:[()=>getCatalog(),value=>saveCatalog(value)],troškovi:[()=>fsGet('v12_expenses',[]),value=>fsSet('v12_expenses',value)],projekti:[()=>fsGet('v12_projects',[]),value=>fsSet('v12_projects',value)],zadaci:[()=>fsGet('v12_tasks',[]),value=>fsSet('v12_tasks',value)],dokumenti:[()=>fsGet('v12_documents',[]),value=>fsSet('v12_documents',value)],ponavljajuće:[()=>fsGet('v12_recurring',[]),value=>fsSet('v12_recurring',value)]
};
const sectionMeta={firma:['Firma','Podaci izdavaoca i logo','F'],postavke:['Postavke','Numeracija, valuta i bankovni podaci','⚙'],klijenti:['Klijenti','Kontakti, države i oznake','K'],fakture:['Fakture','Dokumenti, stavke i uplate','▤'],ponude:['Ponude','Ponude i njihovi statusi','◇'],katalog:['Katalog','Proizvodi, usluge i kategorije','▦'],troškovi:['Troškovi','Evidentirani poslovni troškovi','↓'],projekti:['Projekti','Projekti i povezani podaci','P'],zadaci:['Zadaci','Aktivni i završeni zadaci','✓'],dokumenti:['Dokumenti','Evidencija lokalnih priloga','D'],ponavljajuće:['Ponavljajuće fakture','Rasporedi i šabloni faktura','↻']};
let pendingDataImport=null;

function fullBackupPayload(){return{version:18,createdAt:new Date().toISOString(),company:getCompany(),settings:getSettings(),clients:getClients(),invoices:getInvoices(),offers:getOffers(),catalog:getCatalog(),draft:getDraft(),appearance:fsGet('fs7_invoice_appearance',{}),expenses:fsGet('v12_expenses',[]),projects:fsGet('v12_projects',[]),tasks:fsGet('v12_tasks',[]),documents:fsGet('v12_documents',[]),leads:fsGet('v12_leads',[]),recurring:fsGet('v12_recurring',[]),theme:fsGet(FS_KEYS.theme,'light'),style:fsGet(FS_KEYS.style,{accent:'#f4c400'})}}
function downloadJson(payload,name){const href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=href;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(href),0)}
function exportBackup(){downloadJson(fullBackupPayload(),`fakture-backup-${today()}.json`);toast('Kompletna sigurnosna kopija je preuzeta.')}
function exportSection(key){const handler=sectionHandlers[key];if(!handler)return;downloadJson({version:2,section:key,createdAt:new Date().toISOString(),data:handler[0]()},`fakture-${key}-${today()}.json`);toast(`Sekcija „${sectionMeta[key][0]}” je izvezena.`)}
function openImportExport(){navigate('importexport')}
function sectionCount(key){const value=sectionHandlers[key][0]();if(Array.isArray(value))return`${value.length} zapisa`;return Object.keys(value||{}).length?`${Object.keys(value).length} polja`:'Nema podataka'}
function renderImportExport(){const keys=Object.keys(sectionHandlers);$('viewContainer').innerHTML=`<div class="page import-export-view"><div class="page-heading"><div><h1>Import / Export</h1><p class="page-subtitle">Sigurno prenesite cijeli profil ili samo odabranu grupu podataka.</p></div><button class="btn light" onclick="navigate('settings')">← Nazad u Postavke</button></div><div class="card import-export-hero"><div class="import-export-hero-icon">⇅</div><div><span class="section-kicker">KOMPLETAN PROFIL</span><h2>Sigurnosna kopija svih podataka</h2><p>Obuhvata firmu, dokumente, klijente, katalog i radni prostor. Uvoz nikada ne počinje bez pregleda i potvrde.</p><small>Preporučeni format · JSON · verzija backupa 18</small></div><div class="import-export-hero-actions"><button class="btn light" onclick="exportBackup()">↓ Izvezi sve</button><button class="btn accent" onclick="$('importAllPageFile').click()">↑ Uvezi backup</button></div><input hidden id="importAllPageFile" type="file" accept=".json,application/json" onchange="importBackupFile(event)"></div><div class="import-export-heading"><div><h2>Podaci po sekcijama</h2><p class="page-subtitle">Manji fajlovi za ciljano premještanje podataka između profila.</p></div><span>${keys.length} dostupnih sekcija</span></div><div class="import-export-grid import-export-page-grid">${keys.map(key=>{const meta=sectionMeta[key];return`<article class="card import-export-card"><div class="import-export-card-head"><span class="import-export-card-icon">${meta[2]}</span><span class="import-export-count">${sectionCount(key)}</span></div><div><h3>${meta[0]}</h3><p>${meta[1]}</p></div><div class="import-export-card-actions"><button class="btn light small" onclick="exportSection('${key}')">↓ Izvezi</button><label class="btn light small">↑ Uvezi<input hidden type="file" accept=".json,application/json" onchange="importSectionFile(event,'${key}')"></label></div></article>`}).join('')}</div><div class="import-export-note"><strong>Podaci ostaju lokalni</strong><span>Export pravi novu datoteku i ne mijenja postojeće podatke. Import zamjenjuje samo sadržaj koji potvrdite.</span></div></div>`}
function readImportFile(file,onRead){const reader=new FileReader();reader.onload=()=>{try{onRead(JSON.parse(reader.result))}catch{toast(`Datoteka „${file.name}” nije ispravan JSON backup.`)}};reader.onerror=()=>toast(`Datoteku „${file.name}” nije moguće pročitati.`);reader.readAsText(file)}
function importBackupFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;readImportFile(file,payload=>{const known=['company','settings','clients','invoices','offers','catalog','expenses','projects','tasks','documents','leads','recurring'].filter(key=>payload[key]!==undefined);if(!payload||typeof payload!=='object'||!known.length){toast(`Datoteka „${file.name}” nije prepoznata kao kompletan backup.`);return}pendingDataImport={kind:'full',fileName:file.name,payload};openModal('Potvrda uvoza backupa',`<div class="import-confirm"><strong>Uvozite datoteku „${esc(file.name)}”.</strong><p>Bit će zamijenjeni podaci aktivnog profila samo za sekcije prisutne u ovoj datoteci:</p><div class="import-confirm-sections">${known.map(key=>`<span>${esc(sectionMeta[key]?.[0]||key)}</span>`).join('')}</div><div class="import-warning"><b>Ovu radnju nije moguće opozvati.</b><span>Preporučujemo da prije nastavka izvezete trenutni kompletan backup.</span></div></div>`,`<div class="modal-actions"><button class="btn light" onclick="cancelPendingImport()">Odustani</button><button class="btn danger" onclick="confirmPendingImport()">Uvezi i zamijeni podatke</button></div>`)})}
function importSectionFile(event,key){const file=event.target.files?.[0];event.target.value='';const handler=sectionHandlers[key];if(!file||!handler)return;readImportFile(file,payload=>{if(payload?.section!==key||payload.data===undefined){toast(`Datoteka „${file.name}” nije backup sekcije „${sectionMeta[key][0]}”.`);return}pendingDataImport={kind:'section',key,fileName:file.name,payload:payload.data};openModal('Potvrda uvoza sekcije',`<div class="import-confirm"><strong>Uvozite „${esc(sectionMeta[key][0])}” iz datoteke „${esc(file.name)}”.</strong><p>Postojeći podaci ove sekcije u aktivnom profilu bit će zamijenjeni sadržajem iz datoteke.</p><div class="import-warning"><b>Ovu radnju nije moguće opozvati.</b><span>Ostale sekcije neće biti promijenjene.</span></div></div>`,`<div class="modal-actions"><button class="btn light" onclick="cancelPendingImport()">Odustani</button><button class="btn danger" onclick="confirmPendingImport()">Uvezi sekciju</button></div>`)})}
function cancelPendingImport(){pendingDataImport=null;closeModal()}
function applyFullImport(data){if(data.company)saveCompany(data.company);if(data.settings)saveSettings(data.settings);if(data.clients)saveClients(data.clients);if(data.invoices)saveInvoices(data.invoices);if(data.offers)saveOffers(data.offers);if(data.catalog)saveCatalog(data.catalog);if(data.draft!==undefined)saveDraft(data.draft);if(data.appearance!==undefined)fsSet('fs7_invoice_appearance',data.appearance);if(data.expenses!==undefined)fsSet('v12_expenses',data.expenses);if(data.projects!==undefined)fsSet('v12_projects',data.projects);if(data.tasks!==undefined)fsSet('v12_tasks',data.tasks);if(data.documents!==undefined)fsSet('v12_documents',data.documents);if(data.leads!==undefined)fsSet('v12_leads',data.leads);if(data.recurring!==undefined)fsSet('v12_recurring',data.recurring);if(data.theme)fsSet(FS_KEYS.theme,data.theme);if(data.style)fsSet(FS_KEYS.style,data.style)}
function confirmPendingImport(){if(!pendingDataImport)return;const current=pendingDataImport;try{if(current.kind==='full')applyFullImport(current.payload);else sectionHandlers[current.key][1](current.payload);pendingDataImport=null;closeModal();updateCompanyChrome?.();applyAppearance?.();renderImportExport();toast(current.kind==='full'?'Backup je uspješno uvezen.':'Sekcija je uspješno uvezena.')}catch{toast(`Uvoz datoteke „${current.fileName}” nije uspio. Podaci nisu potvrđeni.`)}}
