function formatDate(value){if(!value)return "—";const m=String(value).match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return `${m[3]}.${m[2]}.${m[1]}.`;const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);return new Intl.DateTimeFormat("bs-BA",{day:"2-digit",month:"2-digit",year:"numeric"}).format(d)}
function formatDateTime(value){if(!value)return "—";const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);return new Intl.DateTimeFormat("bs-BA",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function money(v,c="BAM"){return new Intl.NumberFormat("bs-BA",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)||0)+" "+c}
function calcItems(items){return (items||[]).map(x=>{const qty=+x.qty||0,price=+x.price||0,disc=Math.max(0,+x.discount||0),vat=Math.max(0,+x.vat||0),base=qty*price,after=base-base*disc/100;return {...x,base,after,vatValue:after*vat/100,total:after*(1+vat/100)}})}
function invoiceTotals(items,dt,dv){const rows=calcItems(items),rawBase=rows.reduce((a,x)=>a+x.after,0),globalDiscount=Math.max(0,dt==="fixed"?+dv||0:rawBase*(+dv||0)/100);let remaining=globalDiscount;const discountedRows=rows.map((x,i)=>{const share=rawBase?globalDiscount*(x.after/rawBase):0;const applied=i===rows.length-1?remaining:Math.min(remaining,share);remaining-=applied;const taxable=Math.max(0,x.after-applied),vatValue=taxable*x.vat/100;return {...x,globalDiscount:applied,taxable,vatValue,total:taxable+vatValue}});const subtotal=discountedRows.reduce((a,x)=>a+x.taxable,0),vat=discountedRows.reduce((a,x)=>a+x.vatValue,0);return{rows:discountedRows,subtotal,discount:globalDiscount,vat,total:Math.max(0,subtotal+vat)}}
function nextInvoiceNumber(){const s=getSettings(),year=new Date().getFullYear(),list=getInvoices();let max=(+s.start||1)-1;list.forEach(x=>{const m=String(x.number||"").match(/(\d+)/);if(m)max=Math.max(max,+m[1])});const n=String(max+1).padStart(3,"0");return s.format==="year-slash"?`${year}/${n}`:s.format==="prefix-year"?`${s.prefix}${n}/${year}`:`${n}/${year}`}
function addDays(date,days){const d=new Date(date+"T12:00:00");d.setDate(d.getDate()+Number(days||0));return d.toISOString().slice(0,10)}function today(){return new Date().toISOString().slice(0,10)}
function groupedCurrency(rows){return rows.reduce((a,x)=>{const c=x.currency||"BAM";a[c]=(a[c]||0)+(+x.total||0);return a},{})}
function moneyGroup(rows){const g=groupedCurrency(rows);return Object.entries(g).map(([c,v])=>money(v,c)).join(" · ")||money(0,"BAM")}
