function dashboardRange(){
  const s=fsGet("fs7_dashboard_range",null);
  if(s)return s;
  const d=new Date(),a=new Date(d.getFullYear(),d.getMonth()-5,1),b=new Date(d.getFullYear(),d.getMonth()+1,0);
  return{from:a.toISOString().slice(0,10),to:b.toISOString().slice(0,10)};
}
function inRange(x,a,b){return(!a||x.issueDate>=a)&&(!b||x.issueDate<=b)}
function monthKey(d){return d.toISOString().slice(0,7)}
function monthLabel(k){const m=Number(String(k).slice(5,7));return["jan.","feb.","mar.","apr.","maj","jun.","jul.","avg.","sep.","okt.","nov.","dec."][m-1]||String(m)}
function moneyCompact(v){if(v>=1000000)return`${(v/1000000).toFixed(1)}M`;if(v>=1000)return`${(v/1000).toFixed(v>=10000?0:1)}k`;return Math.round(v)}
function buildRevenueChart(rows,from,to,currency){
  const end=new Date((to||today())+"T12:00:00"),start=new Date((from||today())+"T12:00:00"),months=[];let cur=new Date(start.getFullYear(),start.getMonth(),1),last=new Date(end.getFullYear(),end.getMonth(),1);
  while(cur<=last){months.push(monthKey(cur));cur.setMonth(cur.getMonth()+1)}if(!months.length)months.push(monthKey(start));
  const codes=currency==="all"?[...new Set(rows.filter(x=>effectiveStatus(x)!=="cancelled").map(x=>x.currency||"BAM"))]:[currency],palette=["#ff2742","#1f3044","#4f8aa5","#8f6bd8","#d48734","#4c9a72","#bb5479"],w=920,h=360,left=54,right=28,top=34,bottom=55,innerW=w-left-right,innerH=h-top-bottom,base=top+innerH;
  const series=codes.map((code,i)=>({code,color:palette[i%palette.length],vals:months.map(k=>rows.filter(x=>String(x.issueDate||"").slice(0,7)===k&&effectiveStatus(x)!=="cancelled"&&(x.currency||"BAM")===code).reduce((s,x)=>s+(+x.total||0),0))}));
  const max=Math.max(...series.flatMap(x=>x.vals),1),grid=[0,.25,.5,.75,1].map(q=>{const y=base-q*innerH;return`<line x1="${left}" y1="${y}" x2="${w-right}" y2="${y}" class="chart-grid"/><text x="${left-12}" y="${y+4}" text-anchor="end" class="chart-axis">${moneyCompact(max*q)}</text>`}).join("");
  const xAt=i=>left+(months.length===1?innerW/2:i*innerW/(months.length-1)),yAt=v=>base-(v/max)*innerH;
  const rendered=series.map((s,index)=>{const points=s.vals.map((v,i)=>({v,x:xAt(i),y:yAt(v),m:months[i]})),line=points.map(p=>`${p.x},${p.y}`).join(" "),area=`${left},${base} ${line} ${w-right},${base}`,dots=points.map(p=>`<g class="chart-point" role="button" tabindex="0" aria-label="Otvori fakture za ${monthLabel(p.m)} ${p.m.slice(0,4)}" onclick="openDashboardMonth('${p.m}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openDashboardMonth('${p.m}')}" ><circle cx="${p.x}" cy="${p.y}" r="5" fill="#fff" stroke="${s.color}" stroke-width="3"/><g class="chart-tooltip"><rect x="${p.x-70}" y="${Math.max(4,p.y-58)}" width="140" height="45" rx="9"/><text x="${p.x}" y="${Math.max(4,p.y-58)+18}" text-anchor="middle">${monthLabel(p.m)} ${p.m.slice(0,4)} · ${s.code}</text><text x="${p.x}" y="${Math.max(4,p.y-58)+34}" text-anchor="middle">${money(p.v,s.code)}</text></g></g>`).join("");return`<polygon points="${area}" fill="${s.color}" opacity="${series.length===1?'.10':'.045'}"/><polyline points="${line}" fill="none" stroke="${s.color}" stroke-width="${series.length===1?'3.5':'3'}" stroke-linecap="round" stroke-linejoin="round"/>${dots}`}).join("");
  const labels=months.map((m,i)=>`<text x="${xAt(i)}" y="${h-18}" text-anchor="middle" class="chart-axis">${monthLabel(m)}</text>`).join(""),legend=series.map(s=>`<span><i style="background:${s.color}"></i><b>${s.code}</b> ${money(s.vals.reduce((a,v)=>a+v,0),s.code)}</span>`).join("");
  return`<div class="chart-insights chart-currency-legend">${legend}<span class="chart-count"><b>${rows.length}</b> faktura</span></div><div class="chart-wrap"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMidYMid meet" class="revenue-chart revenue-line-chart">${grid}${rendered}${labels}</svg></div>`;
}
function donutChart(counts,total){
  const items=[['paid','Plaćene','var(--success)'],['partial','Djelimično','var(--accent)'],['sent','Neplaćene','var(--warning)'],['draft','Nacrti','var(--muted)'],['cancelled','Otkazane','var(--danger)']].map(x=>[...x,counts[x[0]]||0]).filter(x=>x[3]>0);
  let offset=0;const circumference=2*Math.PI*52;
  const circles=items.map(x=>{const len=total?x[3]/total*circumference:0;const c=`<circle cx="70" cy="70" r="52" class="donut-segment" stroke="${x[2]}" stroke-dasharray="${len} ${circumference-len}" stroke-dashoffset="${-offset}"/>`;offset+=len;return c}).join("");
  return`<div class="donut-layout"><div class="donut"><svg viewBox="0 0 140 140"><circle cx="70" cy="70" r="52" class="donut-bg"/>${circles}<text x="70" y="68" text-anchor="middle" class="donut-number">${total}</text><text x="70" y="84" text-anchor="middle" class="donut-label">faktura</text></svg></div><div class="legend">${items.map(x=>`<button type="button" class="legend-row" onclick="openDashboardInvoices('${x[0]}')"><span><i style="background:${x[2]}"></i>${x[1]}</span><strong>${x[3]}</strong></button>`).join("")}</div></div>`;
}
function metricIcon(kind){const paths={invoices:'<path d="M7 3h7l4 4v14H7z"/><path d="M14 3v5h5M10 13h5M10 17h5"/>',paid:'<circle cx="12" cy="12" r="8"/><path d="m8.5 12 2.2 2.2 4.8-5"/>',due:'<path d="M5 4h14v16H5z"/><path d="M8 2v4M16 2v4M5 8h14M9 12h3v4"/>',overdue:'<path d="M12 3 21 19H3z"/><path d="M12 9v4M12 16h.01"/>' };return`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${paths[kind]}</svg>`}
function renderDashboard(){
  const r=dashboardRange(),all=getInvoices(),inv=all.filter(x=>inRange(x,r.from,r.to)),active=inv.filter(x=>effectiveStatus(x)!=="cancelled"),paid=active.filter(x=>effectiveStatus(x)==="paid"),partial=active.filter(x=>effectiveStatus(x)==="partial"),unpaid=active.filter(x=>effectiveStatus(x)==="sent"),over=active.filter(isOverdue),counts={draft:0,sent:0,partial:0,paid:0,cancelled:0};
  inv.forEach(x=>counts[effectiveStatus(x)]=(counts[effectiveStatus(x)]||0)+1);
  const recent=all.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,6),attention=[...over,...partial,...unpaid].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i).slice(0,4);
  const clients={};active.forEach(x=>{const key=x.clientName||"Bez klijenta";(clients[key]??=[]).push(x)});
  const top=Object.entries(clients).sort((a,b)=>b[1].length-a[1].length).slice(0,5);
  const attentionHtml=attention.length?attention.map(x=>{const s=statusLabel(effectiveStatus(x),isOverdue(x)),id=JSON.stringify(String(x.id));return`<div class="attention-card"><div class="attention-main"><span class="status-dot ${s[0]}"></span><div><strong>${esc(x.number)} · ${esc(x.clientName||"Bez klijenta")}</strong><small>${money(x.total,x.currency)} · rok ${esc(formatDate(x.dueDate))}</small></div></div><div class="attention-actions"><button class="btn light tiny" onclick='openDashboardInvoice(${id})'>↗ Pregled</button>${effectiveStatus(x)!=="paid"?`<button class="btn success tiny" onclick='openDashboardInvoicePayment(${id})'>＋ Uplata</button>`:""}</div></div>`}).join(""):`<div class="empty compact-empty"><strong>Nema hitnih stavki.</strong><span>Sve fakture su trenutno bez potrebe za dodatnom radnjom.</span></div>`;
  const recentHtml=recent.length?recent.map(x=>{const s=statusLabel(effectiveStatus(x),isOverdue(x)),id=JSON.stringify(String(x.id));return`<tr><td><button class="invoice-number-link" onclick='openDashboardInvoice(${id})'>${esc(x.number)}</button></td><td><strong>${esc(x.clientName||"—")}</strong><small class="cell-sub">${esc(formatDate(x.issueDate))}</small></td><td><strong>${money(x.total,x.currency)}</strong></td><td><span class="status-pill ${s[0]}">${s[1]}</span></td><td>${invoiceRowActions(x)}</td></tr>`}).join(""):'';
  const currencies=[...new Set(active.map(x=>x.currency||"BAM"))];
  $('viewContainer').innerHTML=`<div class="page"><div class="page-heading dashboard-heading"><div><h1>Dashboard</h1><p class="page-subtitle">Stvarni pregled fakturisanja, naplate i radnji koje traže pažnju.</p></div><div class="dashboard-toolbar"><div class="period-picker"><span>Period</span><input id="dashFrom" type="date" value="${r.from}"><b>—</b><input id="dashTo" type="date" value="${r.to}"><button class="btn light tiny" onclick="applyDashboardRange()">Primijeni</button></div><button class="btn accent" onclick="navigate('invoice')">＋ Nova faktura</button></div></div>
  <div class="dashboard-hero-grid"><div class="metric-grid">
    <button type="button" class="card metric metric-blue dashboard-metric-link" onclick="openDashboardInvoices('')"><div class="metric-head"><div class="metric-icon">${metricIcon('invoices')}</div><div class="metric-label">Fakture</div></div><div class="metric-value">${inv.length}</div><div class="metric-foot">u odabranom periodu</div></button>
    <button type="button" class="card metric metric-green dashboard-metric-link" onclick="openDashboardInvoices('paid')"><div class="metric-head"><div class="metric-icon">${metricIcon('paid')}</div><div class="metric-label">Plaćeno</div></div><div class="metric-value">${moneyGroup(paid)}</div><div class="metric-foot">${paid.length} potpuno plaćenih</div></button>
    <button type="button" class="card metric metric-amber dashboard-metric-link" onclick="openDashboardPayments('open')"><div class="metric-head"><div class="metric-icon">${metricIcon('due')}</div><div class="metric-label">Za naplatu</div></div><div class="metric-value">${moneyGroup([...unpaid,...partial])}</div><div class="metric-foot">${unpaid.length+partial.length} otvorenih</div></button>
    <button type="button" class="card metric metric-red dashboard-metric-link" onclick="openDashboardInvoices('overdue')"><div class="metric-head"><div class="metric-icon">${metricIcon('overdue')}</div><div class="metric-label">Dospjelo</div></div><div class="metric-value">${moneyGroup(over)}</div><div class="metric-foot">${over.length} faktura</div></button>
  </div>
  <div class="card dashboard-card chart-card"><div class="section-head"><div><h2>Prihod po mjesecima</h2><p class="page-subtitle">Izdane fakture u odabranom periodu; valute se ne konvertuju.</p></div><select class="chart-currency" id="dashCurrency"><option value="all">Sve valute</option>${currencies.map(c=>`<option>${c}</option>`).join("")}</select></div><div id="revenueChartHost"></div></div></div>
  <div class="dashboard-grid-main"><div class="card dashboard-card"><div class="section-head"><div><h2>Status faktura</h2><p class="page-subtitle">Brzi pregled raspodjele.</p></div><button class="btn light tiny" onclick="navigate('invoices')">Sve fakture</button></div>${donutChart(counts,inv.length)}</div><div class="card dashboard-card"><div class="section-head"><div><h2>Potrebna pažnja</h2><p class="page-subtitle">Radnje koje možete izvršiti direktno iz dashboarda.</p></div></div><div class="attention-list">${attentionHtml}</div></div><div class="card dashboard-card"><div class="section-head"><div><h2>Najaktivniji klijenti</h2><p class="page-subtitle">Po broju faktura i vrijednosti u periodu.</p></div><button class="btn light tiny" onclick="navigate('clients')">Svi klijenti</button></div>${top.length?top.map((x,i)=>{const rows=x[1],last=rows.slice().sort((a,b)=>String(b.issueDate).localeCompare(String(a.issueDate)))[0],avg=rows.reduce((s,y)=>s+(+y.total||0),0)/rows.length,clientIndex=getClients().findIndex(c=>c.name===x[0]);return`<div class="rank-row rank-row-rich"><span class="rank">${i+1}</span><div class="rank-main"><strong>${esc(x[0])}</strong><small>${rows.length} faktura · prosjek ${money(avg,last?.currency||"BAM")}</small><small>Posljednja: ${esc(formatDate(last?.issueDate))} · ${money(last?.total,last?.currency)}</small></div><div class="rank-actions">${clientIndex>=0?`<button class="btn light tiny" onclick="clientProfile(${clientIndex})">Profil</button>`:""}<button class="btn light tiny" onclick="navigate('invoices')">Fakture</button></div></div>`}).join(""):`<div class="empty">Nema podataka.</div>`}</div></div>
  <div class="dashboard-grid-bottom"><div class="card dashboard-card"><div class="section-head"><div><h2>Posljednje fakture</h2><p class="page-subtitle">Najnoviji dokumenti i brze radnje.</p></div><button class="btn light tiny" onclick="navigate('invoices')">Prikaži sve</button></div>${recent.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Broj</th><th>Klijent</th><th>Iznos</th><th>Status</th><th>Radnje</th></tr></thead><tbody>${recentHtml}</tbody></table></div>`:'<div class="empty">Još nema faktura. Kreirajte prvi dokument.</div>'}</div></div></div>`;
  const preferred=getSettings().currency||"BAM";$('dashCurrency').value=currencies.includes(preferred)?preferred:"all";
  $('dashCurrency').onchange=()=>{const host=$("revenueChartHost");if(host)host.innerHTML=buildRevenueChart(active,r.from,r.to,$('dashCurrency').value)};
  const host=$("revenueChartHost");if(host)host.innerHTML=buildRevenueChart(active,r.from,r.to,$('dashCurrency').value);
}
function applyDashboardRange(){const a=$("dashFrom").value,b=$("dashTo").value;if(a>b){toast("Datum 'od' mora biti prije datuma 'do'.");return}fsSet("fs7_dashboard_range",{from:a,to:b});renderDashboard()}
