(function(){
  const base=renderDashboard;
  function range(){return dashboardRange()}
  function metrics(){const r=range(),all=getInvoices().filter(x=>x.issueDate>=r.from&&x.issueDate<=r.to),active=all.filter(x=>!['cancelled','draft'].includes(x.status)&&x.status!=='cancelled'),paid=active.filter(x=>effectiveStatus(x)==='paid'),open=active.filter(x=>!['paid'].includes(effectiveStatus(x))),over=active.filter(isOverdue);return{all,active,paid,open,over}}
  function grouped(rows,fn=x=>+x.total||0){const g={};rows.forEach(x=>{const c=x.currency||'BAM';g[c]=(g[c]||0)+(fn(x)||0)});return Object.entries(g).map(([c,v])=>money(v,c)).join(' · ')||money(0,'BAM')}
  const baseRevenueChart=buildRevenueChart;buildRevenueChart=function(rows,from,to,currency){return baseRevenueChart(rows.filter(x=>(x.status||'sent')!=='draft'),from,to,currency)};
  window.setDashboardQuick=function(kind){const d=new Date(),y=d.getFullYear(),m=d.getMonth();let a,b;if(kind==='month'){a=new Date(y,m,1);b=new Date(y,m+1,0)}else if(kind==='prev'){a=new Date(y,m-1,1);b=new Date(y,m,0)}else{a=new Date(y,0,1);b=new Date(y,11,31)}fsSet('fs7_dashboard_range',{from:a.toISOString().slice(0,10),to:b.toISOString().slice(0,10)});renderDashboard()};
  renderDashboard=function(){base();const m=metrics(),cards=document.querySelectorAll('.dashboard-metric-link');if(cards.length>=4){cards[0].querySelector('.metric-value').textContent=m.active.length;cards[1].querySelector('.metric-value').textContent=grouped(m.paid);cards[2].querySelector('.metric-value').textContent=grouped(m.open,x=>(+x.total||0)-paidAmount(x));cards[3].querySelector('.metric-value').textContent=grouped(m.over,x=>(+x.total||0)-paidAmount(x))}const picker=document.querySelector('.dashboard-toolbar .period-picker');if(picker&&!picker.querySelector('.dashboard-quick-periods'))picker.insertAdjacentHTML('afterbegin','<div class="dashboard-quick-periods"><button class="btn light tiny" onclick="setDashboardQuick(\'month\')">Ovaj mjesec</button><button class="btn light tiny" onclick="setDashboardQuick(\'prev\')">Prošli mjesec</button><button class="btn light tiny" onclick="setDashboardQuick(\'year\')">Ova godina</button></div>');if(!m.active.length){const attention=document.querySelector('.attention-list');if(attention)attention.innerHTML='<div class="empty compact-empty"><strong>Još nema izdatih faktura.</strong><span>Kreirajte prvu fakturu da biste pratili promet i naplatu.</span><button class="btn accent small" onclick="navigate(\'invoice\')">Kreiraj prvu fakturu</button></div>'}};
  window.openDashboardInvoices=function(status){navigate('invoices');setTimeout(()=>{if(typeof setInvoiceTab==='function')setInvoiceTab(status||'')},0)};
  window.openDashboardMonth=function(month){navigate('invoices');setTimeout(()=>{if(typeof setInvoiceFilter==='function')setInvoiceFilter('month',month)},0)};
  window.openDashboardPayments=function(status){navigate('payments');setTimeout(()=>{const s=$('pcStatus');if(s){s.value=status==='open'?'open':status||'';s.dispatchEvent(new Event('change'))}},0)};
  window.openDashboardInvoice=function(id){const invoice=getInvoices().find(x=>String(x.id)===String(id));if(!invoice){toast('Faktura nije pronađena.');return}editInvoice(invoice.id)};
  window.openDashboardInvoicePayment=function(id){const invoice=getInvoices().find(x=>String(x.id)===String(id));if(!invoice){toast('Faktura nije pronađena.');return}recordPaymentModal(invoice.id)};
  routes.dashboard=renderDashboard;setTimeout(()=>{if(location.hash==='#dashboard')renderDashboard()},0);
})();
