function getBrandColor(){return fsGet(FS_KEYS.style,{accent:'#f4c400'}).accent||'#f4c400'}
let invoiceState={items:[]};
function defaultItem(){const s=getSettings(),vatRegistered=getCompany?.().vatRegistered!==false;return{description:"",itemDescription:"",qty:1,price:0,discount:0,vat:vatRegistered?s.defaultVat:0}}
function invoiceBankDefaults(currency){const s=getSettings(),accounts=Array.isArray(s.bankAccounts)?s.bankAccounts.filter(x=>x.status!=='archived'):[],match=accounts.find(x=>x.currency===currency)||accounts.find(x=>x.id===s.defaultBankAccountId)||accounts.find(x=>x.default);return match?{bankAccountId:match.id,bankAccountSnapshot:JSON.parse(JSON.stringify(match))}:{bankAccountId:'',bankAccountSnapshot:null}}
function loadInvoiceState(data=null){const s=getSettings(),d=data||getDraft(),bank=invoiceBankDefaults(d?.currency||s.currency);invoiceState=d?JSON.parse(JSON.stringify(d)):{number:nextInvoiceNumber(),issueDate:today(),dueDate:addDays(today(),s.dueDays),status:"draft",documentLanguage:normalizeDocumentLanguage(s.documentLanguage),currency:s.currency,paymentMethod:s.paymentMethod,clientId:"",clientName:"",clientAddress:"",clientCity:"",clientCountry:"",clientEmail:"",clientIdNo:"",clientVat:"",globalDiscountType:"percent",globalDiscount:0,items:[defaultItem()],milestones:[],note:s.paymentNote,...bank};if(invoiceState.documentLanguage===undefined)invoiceState.documentLanguage=normalizeDocumentLanguage(s.documentLanguage);if(invoiceState.bankAccountSnapshot===undefined)invoiceState.bankAccountSnapshot=bank.bankAccountSnapshot;invoiceState.items=invoiceState.items?.length?invoiceState.items:[defaultItem()];invoiceState.items.forEach(item=>{if(item.itemDescription===undefined)item.itemDescription=''});invoiceState.milestones=Array.isArray(invoiceState.milestones)?invoiceState.milestones:[]}
function persistInvoice(){
 const ok=saveDraft(JSON.parse(JSON.stringify(invoiceState)));
 if($("saveState"))$("saveState").textContent=ok?"✓ Automatski spremljeno · "+new Date().toLocaleTimeString("bs-BA",{hour:"2-digit",minute:"2-digit"}):"⚠ Nije spremljeno";
 if($("topSaveState"))$("topSaveState").textContent=ok?"✓ Sačuvano "+new Date().toLocaleTimeString("bs-BA",{hour:"2-digit",minute:"2-digit"}):"⚠ Nije sačuvano";
 updatePreview();
 return ok;
}
function renderInvoice(data=null){loadInvoiceState(data);const clients=getClients();$("viewContainer").innerHTML=`<div class="page"><div class="page-heading"><div><h1>${invoiceState.id?"Uredi fakturu":"Nova faktura"}</h1><p class="page-subtitle">Popunite podatke i pratite finalni A4 dokument uživo.</p></div><div class="page-actions"><button class="btn light" onclick="newInvoice()">Nova</button><button class="btn light" onclick="printCurrentInvoice()">▣ Ištampaj</button><button class="btn light" onclick="downloadCurrentPdf()">↓ PDF</button><button class="btn light" onclick="invoiceState.id?emailInvoice(invoiceState.id):toast('Prvo sačuvajte fakturu.')">✉ Pošalji</button><button class="btn accent" onclick="saveInvoiceRecord()">Sačuvaj fakturu</button></div></div><div class="invoice-workspace"><div class="invoice-editor">
<div class="card section-card"><div class="section-head"><div class="section-head-left"><div class="step">01</div><div><h3>Dokument</h3><p class="page-subtitle">Broj, datum i način plaćanja</p></div></div><span id="saveState" class="save-state">✓ Spremno</span></div><div class="grid-4"><div class="field"><label>Broj fakture</label><input id="invNumber" value="${esc(invoiceState.number)}"></div><div class="field"><label>Datum izdavanja</label><input id="invIssueDate" type="date" value="${invoiceState.issueDate}"></div><div class="field"><label>Rok plaćanja</label><input id="invDueDate" type="date" value="${invoiceState.dueDate}"></div><div class="field"><label>Status</label><select id="invStatus"><option value="draft">Nacrt</option><option value="sent">Poslano</option><option value="paid">Plaćeno</option><option value="cancelled">Otkazano</option></select></div></div><div class="invoice-status-actions"><span class="status-pill status-draft" id="editorStatusPill">Nacrt</span><button class="btn success tiny" onclick="markCurrentInvoicePaid()">✓ Označi plaćeno</button><button class="btn light tiny" onclick="recordCurrentPayment()">+ Evidentiraj uplatu</button></div><div class="grid-3" style="margin-top:13px"><div class="field"><label>Valuta</label><select id="invCurrency"><option>BAM</option><option>EUR</option><option>USD</option><option>CHF</option></select></div><div class="field"><label>Način plaćanja</label><select id="invPayment"><option>Bankovni transfer</option><option>Gotovina</option><option>Kartica</option><option>PayPal</option><option>Ostalo</option></select></div><div class="field"><label>Globalni popust</label><div style="display:grid;grid-template-columns:1fr 82px;gap:6px"><input id="invDiscount" type="number" min="0" step="0.01"><select id="invDiscountType"><option value="percent">%</option><option value="fixed">Iznos</option></select></div></div></div></div>
<div class="card section-card"><div class="section-head"><div class="section-head-left"><div class="step">02</div><div><h3>Klijent</h3><p class="page-subtitle">Odaberite sačuvanog klijenta ili unesite podatke ručno.</p></div></div><button class="btn light small" onclick="clientModal()">＋ Novi klijent</button></div><div class="client-picker"><div id="clientPicker" class="client-picker-box placeholder" onclick="toggleClientPicker()"><span>Odaberi sačuvanog klijenta...</span></div><button class="btn light" onclick="clearClient()">Očisti</button><div id="clientDropdown" class="client-picker-dropdown" style="display:none"><div class="client-picker-search"><input id="clientPickerSearch" placeholder="Pretraži klijente..."></div><div id="clientOptions"></div></div></div><div class="grid-3" style="margin-top:13px"><div class="field"><label>Naziv / ime</label><input id="clientName" value="${esc(invoiceState.clientName)}"></div><div class="field"><label>Adresa</label><input id="clientAddress" value="${esc(invoiceState.clientAddress)}"></div><div class="field"><label>Grad</label><input id="clientCity" value="${esc(invoiceState.clientCity)}"></div><div class="field"><label>ID broj</label><input id="clientIdNo" value="${esc(invoiceState.clientIdNo)}"></div><div class="field"><label>PDV broj</label><input id="clientVat" value="${esc(invoiceState.clientVat)}"></div><div class="field"><label>Email</label><input id="clientEmail" value="${esc(invoiceState.clientEmail)}"></div></div></div>
<div class="card section-card"><div class="section-head"><div class="section-head-left"><div class="step">03</div><div><h3>Stavke fakture</h3><p class="page-subtitle">Cijene, količine, popusti i PDV.</p></div></div><div style="display:flex;gap:7px"><button class="btn light small" onclick="addCatalogToInvoice()">▦ Iz kataloga</button><button class="btn light small" onclick="addInvoiceItem()">＋ Dodaj stavku</button></div></div><div class="items-table-wrap"><table class="items-table"><thead><tr><th style="width:31%">Opis</th><th>Količina</th><th>Cijena</th><th>Popust</th><th>PDV</th><th>Ukupno</th><th></th></tr></thead><tbody id="itemsBody"></tbody></table></div></div>
<div class="card section-card"><div class="section-head"><div class="section-head-left"><div class="step">04</div><div><h3>Napomena</h3><p class="page-subtitle">Tekst koji će biti prikazan na dokumentu.</p></div></div></div><div class="field"><label>Napomena / uslovi plaćanja</label><textarea id="invNote">${esc(invoiceState.note||"")}</textarea></div></div>
<div class="card section-card"><div class="section-head"><div class="section-head-left"><div class="step">05</div><div><h3>Plan plaćanja na rate</h3><p class="page-subtitle">Opcionalno: unaprijed dogovoreni milestones i rokovi plaćanja.</p></div></div><button class="btn light small" onclick="addMilestone()">＋ Dodaj ratu</button></div><div id="milestonesBody"></div></div>
<div class="invoice-bottom"><span class="save-state">Podaci se čuvaju lokalno u ovom browseru.</span><div class="invoice-shortcuts"><span>Ctrl+S za spremanje</span><span>Ctrl+P za štampu</span></div></div></div>
<div class="preview-sticky"><div class="preview-head"><div><h2>Pregled dokumenta</h2><p class="page-subtitle">A4 format · spremno za štampu</p></div><span class="status-pill status-draft" id="previewStatus">Nacrt</span></div><div class="preview-shell"><div id="a4Preview" class="a4-preview"></div></div></div></div></div>`;$('invStatus').value=invoiceState.status;$('invCurrency').value=invoiceState.currency;$('invPayment').value=invoiceState.paymentMethod;$('invDiscount').value=invoiceState.globalDiscount||0;$('invDiscountType').value=invoiceState.globalDiscountType||'percent';bindInvoiceInputs();renderItems();renderClientOptions();updatePreview()}
function bindInvoiceInputs(){const ids=["invNumber","invIssueDate","invDueDate","invStatus","invCurrency","invPayment","invDiscount","invDiscountType","clientName","clientAddress","clientCity","clientIdNo","clientVat","clientEmail","invNote"];ids.forEach(id=>$(id).addEventListener("input",syncInvoiceFromForm));ids.forEach(id=>$(id).addEventListener("change",syncInvoiceFromForm));$("clientPickerSearch").oninput=renderClientOptions;document.addEventListener("click",invoiceOutsideClick,{once:false})}
function invoiceOutsideClick(e){const p=$("clientPicker"),d=$("clientDropdown");if(d&&p&&!p.contains(e.target)&&!d.contains(e.target))d.style.display="none"}
function toggleClientPicker(){const d=$("clientDropdown");d.style.display=d.style.display==="none"?"block":"none";if(d.style.display==="block")$("clientPickerSearch").focus()}
function renderClientOptions(){const box=$("clientOptions");if(!box)return;const q=($("clientPickerSearch").value||"").toLowerCase();const a=getClients().map((c,i)=>({c,i})).filter(x=>(x.c.name||"").toLowerCase().includes(q)||(x.c.email||"").toLowerCase().includes(q));box.innerHTML=a.length?a.map(({c,i})=>`<button class="client-option" onclick="selectClient(${i})"><span class="client-option-avatar">${initials(c.name)}</span><span><strong>${esc(c.name)}</strong><small>${esc(c.email||c.city||"Bez dodatnih podataka")}</small></span></button>`).join(""):`<div class="empty" style="padding:24px 12px">Nema klijenata.</div>`}
function selectClient(i){const c=getClients()[i];if(!c)return;Object.assign(invoiceState,{clientId:i,clientName:c.name||"",clientAddress:c.address||"",clientCity:c.city||"",clientIdNo:c.id||"",clientVat:c.vat||"",clientEmail:c.email||""});["clientName","clientAddress","clientCity","clientIdNo","clientVat","clientEmail"].forEach(id=>$(id).value=invoiceState[id]);$("clientPicker").classList.remove("placeholder");$("clientPicker").innerHTML=`<span>${esc(c.name)}</span>`;$("clientDropdown").style.display="none";persistInvoice()}
function syncInvoiceFromForm(){Object.assign(invoiceState,{number:$('invNumber').value,issueDate:$('invIssueDate').value,dueDate:$('invDueDate').value,status:$('invStatus').value,currency:$('invCurrency').value,paymentMethod:$('invPayment').value,globalDiscount:+$('invDiscount').value||0,globalDiscountType:$('invDiscountType').value,clientName:$('clientName').value,clientAddress:$('clientAddress').value,clientCity:$('clientCity').value,clientIdNo:$('clientIdNo').value,clientVat:$('clientVat').value,clientEmail:$('clientEmail').value,note:$('invNote').value});persistInvoice()}
function renderItems(){const body=$("itemsBody");body.innerHTML=invoiceState.items.map((x,i)=>`<tr><td><input data-item="${i}" data-k="description" value="${esc(x.description)}" placeholder="Opis stavke"></td><td><input class="num" type="number" min="0" step="0.01" data-item="${i}" data-k="qty" value="${x.qty}"></td><td><input class="num" type="number" min="0" step="0.01" data-item="${i}" data-k="price" value="${x.price}"></td><td><input class="num" type="number" min="0" step="0.01" data-item="${i}" data-k="discount" value="${x.discount}"></td><td><input class="num" type="number" min="0" step="0.01" data-item="${i}" data-k="vat" value="${x.vat}"></td><td id="itemTotal${i}"><strong>${money((+x.qty||0)*(+x.price||0)*(1-(+x.discount||0)/100)*(1+(+x.vat||0)/100),invoiceState.currency)}</strong></td><td><button class="remove-item" onclick="removeInvoiceItem(${i})">×</button></td></tr>`).join("");body.querySelectorAll("[data-item]").forEach(el=>el.addEventListener("input",e=>{const i=+e.target.dataset.item,k=e.target.dataset.k;invoiceState.items[i][k]=k==="description"?e.target.value:+e.target.value||0;persistInvoice();updateItemTotal(i);updatePreview()}));renderMilestones()}
function renderMilestones(){const box=$("milestonesBody");if(!box)return;const a=invoiceState.milestones||[];box.innerHTML=a.length?`<div class="items-table-wrap"><table class="items-table"><thead><tr><th>Opis rate</th><th>Rok</th><th>Iznos</th><th>Status</th><th></th></tr></thead><tbody>${a.map((m,i)=>`<tr><td><input value="${esc(m.name||"")}" placeholder="npr. Avans" onchange="updateMilestone(${i},'name',this.value)"></td><td><input type="date" value="${esc(m.dueDate||"")}" onchange="updateMilestone(${i},'dueDate',this.value)"></td><td><input class="num" type="number" min="0" step="0.01" value="${+m.amount||0}" onchange="updateMilestone(${i},'amount',this.value)"></td><td><select onchange="updateMilestone(${i},'status',this.value)"><option value="pending" ${m.status!=="paid"?"selected":""}>Na čekanju</option><option value="paid" ${m.status==="paid"?"selected":""}>Plaćeno</option></select></td><td><button class="remove-item" onclick="removeMilestone(${i})">×</button></td></tr>`).join("")}</tbody></table></div><div class="field-hint">Ukupno rata: <strong>${money(a.reduce((s,m)=>s+(+m.amount||0),0),invoiceState.currency)}</strong>. Iznos rata može se razlikovati od ukupne fakture ako ga tek planirate.</div>`:`<div class="empty compact-empty">Nema definisanih rata. Dodajte ih samo kada je plaćanje dogovoreno u više dijelova.</div>`}
function addMilestone(){invoiceState.milestones.push({id:`milestone_${Date.now()}_${invoiceState.milestones.length}`,name:`Rata ${invoiceState.milestones.length+1}`,dueDate:invoiceState.dueDate,amount:0,paidAmount:0,status:"pending"});persistInvoice();renderMilestones()}
function updateMilestone(i,key,value){const m=invoiceState.milestones?.[i];if(!m)return;m[key]=key==="amount"?Math.max(0,+value||0):value;persistInvoice();renderMilestones()}
function removeMilestone(i){invoiceState.milestones.splice(i,1);persistInvoice();renderMilestones()}
function updateItemTotal(i){const x=invoiceState.items[i],e=$("itemTotal"+i);if(e)e.innerHTML=`<strong>${money((+x.qty||0)*(+x.price||0)*(1-(+x.discount||0)/100)*(1+(+x.vat||0)/100),invoiceState.currency)}</strong>`}
function addInvoiceItem(){invoiceState.items.push(defaultItem());persistInvoice();renderItems()}
function addCatalogToInvoice(){const a=getCatalog?.()||[];if(!a.length){toast("Katalog je prazan. Prvo dodajte stavku u Katalog.");return}openModal("Dodaj iz kataloga",`<div style="display:grid;gap:7px">${a.map((x,i)=>`<button class="client-option" onclick="chooseCatalogItem(${i})"><span class="client-option-avatar">${x.type==="Proizvod"?"P":"U"}</span><span><strong>${esc(x.name)}</strong><small>${money(x.price,x.currency)} · PDV ${x.vat}%</small></span></button>`).join("")}</div>`)}
function chooseCatalogItem(i){const x=getCatalog()[i];if(!x)return;invoiceState.items.push({description:x.description||x.name,qty:1,price:x.price,discount:+x.discount||0,vat:x.vat});saveDraft(invoiceState);closeModal();renderItems();updatePreview();toast("Stavka je dodana u fakturu.")}
function removeInvoiceItem(i){if(invoiceState.items.length===1){toast("Mora postojati barem jedna stavka.");return}invoiceState.items.splice(i,1);persistInvoice();renderItems()}
function clearClient(){Object.assign(invoiceState,{clientId:"",clientName:"",clientAddress:"",clientCity:"",clientIdNo:"",clientVat:"",clientEmail:""});["clientName","clientAddress","clientCity","clientIdNo","clientVat","clientEmail"].forEach(id=>$(id).value="");$("clientPicker").className="client-picker-box placeholder";$("clientPicker").innerHTML="<span>Odaberi sačuvanog klijenta...</span>";syncInvoiceFromForm()}
function updatePreview(){
 if(!$('a4Preview'))return;
 const c=invoiceState.companySnapshot||getCompany(),t=invoiceTotals(invoiceState.items,invoiceState.globalDiscountType,invoiceState.globalDiscount),st=statusLabel(effectiveStatus(invoiceState),isOverdue(invoiceState)),bc=getBrandColor(),saved=getAppearance(),a={...saved};
 $('previewStatus').className=`status-pill ${st[0]}`;$('previewStatus').textContent=st[1];
 if($('editorStatusPill')){$('editorStatusPill').className=`status-pill ${st[0]}`;$('editorStatusPill').textContent=st[1]}
 const template=a.template||'studio';
 const logo=a.showLogo!==false?(c.logo?`<img src="${c.logo}" alt="">`:`<span>${esc(c.name||'VAŠA FIRMA')}</span>`):'';
 const vatHead=a.showVat!==false?'<th>PDV</th>':'';
 const vatCells=a.showVat!==false?'<td>${r.vat}%</td>':'';
 const vatSummary=a.showVat!==false?`<div class="a4-total"><span>PDV</span><span>${money(t.vat,invoiceState.currency)}</span></div>`:'';
 const payment=a.showPayment!==false?`Način plaćanja: ${esc(invoiceState.paymentMethod||'—')}`:'';
 const note=a.showNote!==false?esc(invoiceState.note||''):'';
 const clientEmail=a.showClientEmail!==false&&invoiceState.clientEmail?`<br>${esc(invoiceState.clientEmail)}`:'';
 const labels={...appearanceDefaults.labels,...(a.labels||{})};
 const companyAddress=a.showCompanyAddress!==false;
 const companyInfo=`${a.showCompanyPhone!==false?`<span>${esc(c.phone||'—')}</span>`:''}${a.showCompanyEmail!==false?`<span>${esc(c.email||'')}</span>`:''}${a.showCompanyWeb!==false?'<span>Fakture · woxdzn.com</span>':''}${a.showCompanyId!==false?`<span>ID/PDV: ${esc(c.vat||c.id||'—')}</span>`:''}${a.footerText?`<p>${esc(a.footerText)}</p>`:''}`;
 const logoHtml=a.showLogo!==false?(c.logo?`<img src="${c.logo}" alt="Logo">`:`<div class="sample-logo-mark" style="background:${esc(bc)};${contrastText(bc)}">${esc(initials(c.name||'F'))}</div><strong>${esc(c.name||'VAŠA FIRMA')}</strong>`):`<strong>${esc(c.name||'VAŠA FIRMA')}</strong>`;
 $('a4Preview').innerHTML=`<div class="sample-a4 invoice-live-preview template-${template}">
   <div class="sample-top"><div class="sample-brand">${logoHtml}<span>${companyAddress?`${esc(c.address||'')} · ${esc(c.city||'')}`:''}${a.showCompanyEmail!==false?` · ${esc(c.email||'')}`:''}</span></div><div class="sample-title"><strong>${esc(labels.invoice)}</strong><b>${esc(invoiceState.number||'—')}</b><span>Izdano ${esc(formatDate(invoiceState.issueDate))}</span><span>Rok plaćanja ${esc(formatDate(invoiceState.dueDate))}</span></div></div>
   <div class="sample-parties"><div><small>${esc(labels.issuer)}</small><strong>${esc(c.name||'VAŠA FIRMA')}</strong>${companyAddress?`<span>${esc(c.address||'—')}</span><span>${esc(c.city||'')}</span>`:''}${a.showCompanyEmail!==false?`<span>${esc(c.email||'')}</span>`:''}${a.showCompanyPhone!==false?`<span>${esc(c.phone||'')}</span>`:''}${a.showCompanyId!==false?`<span>ID/PDV: ${esc(c.vat||c.id||'—')}</span>`:''}</div><div><small>${esc(labels.client)}</small><strong>${esc(invoiceState.clientName||'Nije odabran')}</strong>${a.showClientAddress!==false?`<span>${esc(invoiceState.clientAddress||'—')}</span><span>${esc(invoiceState.clientCity||'')}</span>`:''}${a.showClientEmail!==false&&invoiceState.clientEmail?`<span>${esc(invoiceState.clientEmail)}</span>`:''}</div></div>
   <table><thead><tr style="background:${esc(bc)};${contrastText(bc)}"><th>${esc(labels.items)}</th><th>Količina</th><th>Cijena</th>${a.showVat!==false?'<th>PDV</th>':''}<th>Ukupno</th></tr></thead><tbody>${t.rows.map(r=>`<tr><td class="document-item-copy"><strong>${esc(r.description||'Stavka')}</strong>${r.itemDescription?`<small>${esc(r.itemDescription)}</small>`:''}</td><td>${r.qty}${r.unit?' '+esc(r.unit):''}</td><td>${money(r.price,invoiceState.currency)}</td>${a.showVat!==false?`<td>${r.vat}%</td>`:''}<td>${money(r.total,invoiceState.currency)}</td></tr>`).join('')}</tbody></table>
   <div class="sample-summary"><div class="summary-lines"><span><em>Međuzbir</em><b>${money(t.subtotal+t.discount,invoiceState.currency)}</b></span>${t.discount?`<span><em>Popust</em><b>−${money(t.discount,invoiceState.currency)}</b></span>`:''}${a.showVat!==false?`<span><em>PDV</em><b>${money(t.vat,invoiceState.currency)}</b></span>`:''}</div><div class="sample-total" style="background:${esc(bc)};${contrastText(bc)}"><span>UKUPNO</span><strong>${money(t.total,invoiceState.currency)}</strong></div></div>
   <div class="sample-bottom"><div><small>NAČIN PLAĆANJA</small><span>${a.showPayment!==false?esc(invoiceState.paymentMethod||'—'):'—'}</span>${a.showPayment!==false&&invoiceState.bankAccountSnapshot?`<p>${esc(invoiceState.bankAccountSnapshot.bank||invoiceState.bankAccountSnapshot.bankName||'')}<br>${esc(invoiceState.bankAccountSnapshot.iban||invoiceState.bankAccountSnapshot.number||'')}${invoiceState.bankAccountSnapshot.swift?'<br>SWIFT: '+esc(invoiceState.bankAccountSnapshot.swift):''}</p>`:''}${a.showNote!==false&&invoiceState.note?`<p>${esc(invoiceState.note)}</p>`:''}</div><div><small>PODACI FIRME</small>${companyInfo}</div></div>
 </div>`
}
function contrastText(hex){const h=hex.replace('#','');if(h.length!==6)return'color:#111';const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),b=parseInt(h.slice(4,6),16),lum=(r*299+g*587+b*114)/1000;return lum<150?'color:#fff':'color:#111'}
function validateInvoice(){if(!invoiceState.clientName.trim()){toast("Unesite ili odaberite klijenta.");return false}if(!invoiceState.items.some(x=>(+x.qty||0)>0&&((+x.price||0)>0))){toast("Dodajte barem jednu stavku sa cijenom.");return false}return true}
function saveInvoiceRecord(){
 syncInvoiceFromForm();
 if(!validateInvoice())return false;
 const t=invoiceTotals(invoiceState.items,invoiceState.globalDiscountType,invoiceState.globalDiscount);
 const list=getInvoices().slice();
 const now=Date.now();
 let id=invoiceState.id||now;
 const record={...JSON.parse(JSON.stringify(invoiceState)),id,total:t.total,createdAt:invoiceState.createdAt||now,updatedAt:now,savedAt:now};
 const existing=list.findIndex(x=>String(x.id)===String(id));
 if(existing>=0)list[existing]=record;else list.unshift(record);
 try{
   if(!saveInvoices(list))throw new Error("Localno spremanje nije uspjelo.");
   const check=getInvoices();
   if(!check.some(x=>String(x.id)===String(id)))throw new Error('Localno spremanje nije potvrđeno.');
   invoiceState.id=id;invoiceState.createdAt=record.createdAt;
   // A saved record must not remain the draft for the next new invoice.
   saveDraft(null);
   updateInvoiceBadge();
   toast(existing>=0?'Faktura je ažurirana.':'Faktura je sačuvana.');
   navigate('invoices');
   return true;
 }catch(e){console.error(e);toast('Greška pri spremanju fakture. Provjerite dozvolu za localStorage.');return false}
}
function newInvoice(){confirmAction("Kreirati novu fakturu? Trenutni nespremljeni nacrt bit će zamijenjen.",()=>{saveDraft(null);renderInvoice()})}
function editInvoice(id){const x=getInvoices().find(i=>String(i.id)===String(id));if(x){saveDraft(x);navigate("invoice")}}
function duplicateInvoice(id){const x=getInvoices().find(i=>String(i.id)===String(id));if(!x)return;const d=JSON.parse(JSON.stringify(x)),now=Date.now();d.id=now;d.number=nextInvoiceNumber();d.issueDate=today();d.dueDate=addDays(today(),getSettings().dueDays);d.status="draft";d.paidAmount=0;d.payments=[];d.createdAt=now;d.updatedAt=now;const list=getInvoices();list.unshift(d);if(!saveInvoices(list)){toast("Kopija nije spremljena.");return}updateInvoiceBadge();refreshCurrentView();toast(`Kopija ${d.number} je kreirana kao nacrt.`)}
function deleteInvoice(id){confirmAction("Obrisati ovu fakturu? Ova radnja se ne može poništiti.",()=>{saveInvoices(getInvoices().filter(i=>i.id!==id));updateInvoiceBadge();renderHistory();toast("Faktura je obrisana.")})}

function markCurrentInvoicePaid(){if(!invoiceState.id){syncInvoiceFromForm();saveInvoiceRecord();return}markInvoicePaid(invoiceState.id);invoiceState.paidAmount=invoiceState.total||invoiceTotals(invoiceState.items,invoiceState.globalDiscountType,invoiceState.globalDiscount).total;invoiceState.status="paid";if($("invStatus"))$("invStatus").value="paid";updatePreview()}
function recordCurrentPayment(){if(!invoiceState.id){toast("Prvo sačuvajte fakturu, pa evidentirajte uplatu.");return}recordPaymentModal(invoiceState.id)}
const renderInvoiceBase=renderInvoice;renderInvoice=function(data=null){renderInvoiceBase(data);const actions=document.querySelector('#viewContainer .page-actions');if(!actions)return;const print=[...actions.querySelectorAll('button')].find(x=>x.textContent.includes('Ištampaj')),email=[...actions.querySelectorAll('button')].find(x=>x.textContent.includes('Pošalji'));if(print&&email)print.insertAdjacentElement('afterend',email)};
