(function(){
  const periods=[['weekly','Sedmično'],['monthly','Mjesečno'],['quarterly','Kvartalno'],['semiannual','Polugodišnje'],['yearly','Godišnje'],['custom','Custom']];
  const rows=()=>fsGet('v12_recurring',[]);
  const periodLabel=v=>periods.find(x=>x[0]===v)?.[1]||v||'Mjesečno';
  const nextDate=(date,period,count=1)=>{const d=new Date(`${date}T12:00:00`);if(period==='weekly')d.setDate(d.getDate()+7*count);else if(period==='monthly')d.setMonth(d.getMonth()+count);else if(period==='quarterly')d.setMonth(d.getMonth()+3*count);else if(period==='semiannual')d.setMonth(d.getMonth()+6*count);else if(period==='yearly')d.setFullYear(d.getFullYear()+count);return d.toISOString().slice(0,10)};
  function normalize(){const list=rows();let changed=false;const out=list.map(x=>{const r={...x};if(!r.id){r.id=`rec_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;changed=true}if(!r.periodKey){r.periodKey=periods.find(p=>p[1]===r.period)?.[0]||'monthly';changed=true}if(!r.startDate){r.startDate=r.next||today();changed=true}if(r.active===undefined){r.active=true;changed=true}if(!Array.isArray(r.generated)){r.generated=[];changed=true}return r});if(changed)fsSet('v12_recurring',out);return out}
  function status(r){if(r.status==='completed'||r.endDate&&r.next>r.endDate||r.maxGenerations&&r.generated.length>=r.maxGenerations)return'completed';return r.active===false?'paused':'active'}
  function statusLabel(v){return{active:'Aktivno',paused:'Pauzirano',completed:'Završeno'}[v]||'Aktivno'}
  renderRecurring=function(){const list=normalize();$('viewContainer').innerHTML=`<div class="page recurring-page"><div class="page-heading"><div><h1>Ponavljajuće fakture</h1><p class="page-subtitle">Šabloni ostaju odvojeni od stvarnih faktura. Generisanje kreira novi originalni dokument.</p></div><button class="btn accent" onclick="addRecurring()">＋ Novi raspored</button></div><div class="card card-pad"><div class="table-wrap"><table class="table"><thead><tr><th>Klijent</th><th>Opis šablona</th><th>Period</th><th>Sljedeća faktura</th><th>Posljednje generisano</th><th>Status</th><th class="actions-head">RADNJE</th></tr></thead><tbody>${list.length?list.map((r,i)=>{const st=status(r),last=r.lastGeneratedAt||r.generated?.slice(-1)[0]?.date;return`<tr><td><strong>${esc(r.client||r.template?.clientName||'—')}</strong></td><td>${esc(r.description||r.template?.items?.[0]?.description||'Šablon fakture')}</td><td>${esc(periodLabel(r.periodKey))}${r.periodKey==='custom'?` · ${r.periodCount||1} ${r.periodUnit==='weeks'?'sedm.':'mj.'}`:''}</td><td>${esc(r.next?formatDate(r.next):'—')}</td><td>${last?esc(formatDate(last)):'—'}</td><td><span class="status-pill ${st==='active'?'status-paid':st==='paused'?'status-draft':'status-cancelled'}">${statusLabel(st)}</span></td><td class="actions-head"><div class="row-actions recurring-actions"><button class="btn accent tiny" onclick="generateRecurring(${i},true)">Generiši sada</button>${st==='active'?`<button class="btn light tiny" onclick="toggleRecurring(${i})">Pauza</button>`:st==='paused'?`<button class="btn success tiny" onclick="toggleRecurring(${i})">Nastavi</button>`:''}<button class="btn light tiny" onclick="editRecurring(${i})">Uredi</button><button class="btn light tiny" onclick="recurringHistory(${i})">Historija (${r.generated?.length||0})</button><button class="btn danger tiny" onclick="deleteRecurring(${i})">Obriši</button></div></td></tr>`}).join(''):`<tr><td colspan="7"><div class="empty">Još nema ponavljajućih faktura.</div></td></tr>`}</tbody></table></div></div></div>`;ensureWorkspaceActions?.('recurring')};
  function enhanceEditor(index){const host=$('recurringPeriod')?.closest('.recurring-template-card');if(!host||host.querySelector('#recurringStart'))return;host.querySelector('.grid-3').insertAdjacentHTML('beforeend',`<div class="field"><label>Datum početka</label><input id="recurringStart" type="date" value="${esc(recurringTemplateContext.start||today())}"></div><div class="field"><label>Datum završetka</label><input id="recurringEnd" type="date" value="${esc(recurringTemplateContext.end||'')}"><small class="field-hint">Ostavite prazno za „Bez datuma završetka“.</small></div><div class="field"><label>Maksimalan broj generisanja</label><input id="recurringMax" type="number" min="0" value="${esc(recurringTemplateContext.max||'')}" placeholder="Bez ograničenja"></div><div class="field" style="grid-column:1/-1"><span class="field-hint">Izmjene šablona utiču samo na buduće fakture. Već generisani dokumenti ostaju nepromijenjeni.</span></div>`);$('recurringPeriod').innerHTML=periods.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('recurringPeriod').value=recurringTemplateContext.periodKey||'monthly';$('recurringStart').value=recurringTemplateContext.start||today();$('recurringEnd').value=recurringTemplateContext.end||'';$('recurringMax').value=recurringTemplateContext.max||'';$('recurringPeriod').onchange=()=>{const p=$('recurringPeriod').value;document.querySelector('.recurring-custom-fields')?.remove();if(p==='custom')$('recurringPeriod').closest('.grid-3').insertAdjacentHTML('beforeend','<div class="field recurring-custom-fields"><label>Jedinica</label><select id="recurringUnit"><option value="months">Mjeseci</option><option value="weeks">Sedmice</option></select></div><div class="field recurring-custom-fields"><label>Broj jedinica</label><input id="recurringCount" type="number" min="1" value="1"></div>')}}
  const baseShow=showRecurringTemplateEditor;showRecurringTemplateEditor=function(index=null){const data=normalize()[index??-1]||{},meta={periodKey:data.periodKey||'monthly',start:data.startDate||data.next||today(),end:data.endDate||'',max:data.maxGenerations||''};baseShow(index);Object.assign(recurringTemplateContext,meta);setTimeout(()=>enhanceEditor(index),0)};
  saveRecurringTemplate=function(){syncInvoiceFromForm();if(!validateInvoice())return;const list=normalize(),ctx=recurringTemplateContext||{},index=ctx.index,old=index===null?{}:list[index]||{},period=$('recurringPeriod')?.value||'monthly',record={...old,id:old.id||`rec_${Date.now()}`,client:invoiceState.clientName,description:invoiceState.items[0]?.description||'Ponavljajuća faktura',amount:invoiceTotals(invoiceState.items,invoiceState.globalDiscountType,invoiceState.globalDiscount).total,currency:invoiceState.currency,periodKey:period,period:periodLabel(period),periodUnit:$('recurringUnit')?.value||old.periodUnit||'months',periodCount:+$('recurringCount')?.value||old.periodCount||1,startDate:$('recurringStart')?.value||today(),next:$('recurringStart')?.value||today(),endDate:$('recurringEnd')?.value||'',maxGenerations:+$('recurringMax')?.value||0,active:$('recurringActive')?.value!=='false',template:JSON.parse(JSON.stringify({...invoiceState,id:undefined,number:'ŠABLON'})),generated:old.generated||[],updatedAt:Date.now()};if(index===null)list.unshift(record);else list[index]=record;fsSet('v12_recurring',list);recurringTemplateContext=null;recurringPreviousDraft=null;saveDraft(null);navigate('recurring');toast('Raspored i šablon su sačuvani.');};
  toggleRecurring=function(index){const list=normalize(),r=list[index];if(!r)return;r.active=status(r)==='paused';r.updatedAt=Date.now();fsSet('v12_recurring',list);renderRecurring();toast(r.active?'Raspored je nastavljen.':'Raspored je pauziran.')};
  generateRecurring=function(index,forceNow=false){const list=normalize(),r=list[index];if(!r)return;const st=status(r);if(st==='completed'){toast('Ovaj raspored je završen.');return}if(!forceNow&&r.next>today()){toast(`Sljedeća faktura je planirana za ${formatDate(r.next)}.`);return}const periodDate=r.next||today(),already=r.generated?.some(x=>x.period===periodDate);if(already){toast('Faktura za ovaj period je već generisana.');return}const template=JSON.parse(JSON.stringify(r.template||{})),now=Date.now(),invoice={...template,id:now,number:nextInvoiceNumber(),issueDate:today(),dueDate:addDays(today(),getSettings().dueDays),status:'draft',createdAt:now,updatedAt:now,recurringId:r.id,recurringPeriod:periodDate};delete invoice.generated;const invoices=getInvoices();invoices.unshift(invoice);saveInvoices(invoices);r.generated=r.generated||[];r.generated.push({invoiceId:invoice.id,number:invoice.number,date:today(),period:periodDate});r.lastGeneratedAt=today();const next=nextDate(periodDate,r.periodKey,r.periodKey==='custom'?r.periodCount||1:1);r.next=next;if(r.endDate&&next>r.endDate||r.maxGenerations&&r.generated.length>=r.maxGenerations)r.status='completed';fsSet('v12_recurring',list);renderRecurring();toast(`Faktura ${invoice.number} je generisana.`)};
  recurringHistory=function(index){const r=normalize()[index];if(!r)return;openModal(`Historija · ${r.client||'Raspored'}`,`<div class="recurring-history-list">${r.generated?.length?r.generated.slice().reverse().map(x=>`<button class="calendar-event-button recurring-history-item" onclick="closeModal();editInvoice('${esc(x.invoiceId)}')"><span><strong>${esc(x.number||'Faktura')}</strong><small>${esc(formatDate(x.date))} · Period ${esc(formatDate(x.period))}</small></span><span>›</span></button>`).join(''):'<div class="empty">Još nema generisanih faktura.</div>'}</div>`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Zatvori</button></div>`)};
  deleteRecurring=function(index){const r=normalize()[index];if(!r)return;confirmDestructive('Obrisati raspored?',`Brišete samo šablon rasporeda „${r.client||'bez klijenta'}“. Već generisane fakture ostaju sačuvane.`,()=>{const list=normalize();list.splice(index,1);fsSet('v12_recurring',list);renderRecurring();toast('Raspored je obrisan, generisane fakture su sačuvane.')})};
  function checkDue(){const due=normalize().filter(r=>status(r)==='active'&&r.next&&r.next<=today());if(due.length)toast(`${due.length} ponavljajućih rasporeda čeka generisanje.`)}
  routes.recurring=renderRecurring;setTimeout(checkDue,900);
})();
