function $(id){return document.getElementById(id)}
const FS_CURRENCIES=["BAM","EUR","USD","CHF","GBP","RSD"];
function normalizeCurrencySelect(select){if(!select||select.dataset.currencyReady)return;const legacy=[...select.options].find(o=>o.value==="KM");if(legacy){legacy.value="BAM";legacy.textContent="BAM";if(select.value==="KM")select.value="BAM"}FS_CURRENCIES.forEach(c=>{if(![...select.options].some(o=>o.value===c)){const o=document.createElement("option");o.value=c;o.textContent=c;select.appendChild(o)}});select.dataset.currencyReady="1"}
document.addEventListener("focusin",e=>{if(e.target?.tagName==="SELECT"&&/Currency|currency/i.test(e.target.id))normalizeCurrencySelect(e.target)});
new MutationObserver(()=>document.querySelectorAll('select[id*="Currency"],select[id*="currency"]').forEach(normalizeCurrencySelect)).observe(document.documentElement,{childList:true,subtree:true});
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;",'\'':"&#039;"}[m]))}
function initials(n){return String(n||"F").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"F"}
let toastTimer;function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),2300)}
function companyAccountNumber(){const settings=getSettings?.()||{},explicit=String(settings.accountNumber||"").trim();if(explicit)return explicit;const bank=String(settings.bank||"").trim(),iban=bank.match(/(?:IBAN\s*:\s*)?((?:[A-Z]{2}\s*\d[\d\s-]{10,})+)/i);return(iban?.[1]||bank.split(/\r?\n/).find(x=>/račun|account|iban/i.test(x))||bank).replace(/^(?:IBAN|račun|account)\s*:\s*/i,"").trim()}
function updateCompanyChrome(){const c=getCompany(),n=c.name||"Moja firma",accountNumber=companyAccountNumber(); updateProfileMetaFromCompany?.();$("sidebarCompanyName").textContent=n;$("topCompanyName").textContent=n;const account=$("topCompanyAccount");if(account)account.textContent=accountNumber||"Račun nije postavljen";$("sidebarCompanyEmail").textContent=c.email||"Podaci firme";$("sidebarCompanyAvatar").textContent=initials(n);$("topCompanyAvatar").textContent=initials(n);updateInvoiceBadge?.()}
function copyCompanyBank(){const account=companyAccountNumber();if(!account){toast("Broj računa nije postavljen.");return}navigator.clipboard?.writeText(account).then(()=>toast("Broj računa je kopiran.")).catch(()=>toast("Kopiranje nije dostupno."))}
function paidAmount(x){return Math.max(0,Math.min(+x.total||0,+x.paidAmount||0))}
function effectiveStatus(x){if(x.status==="cancelled")return "cancelled";if(paidAmount(x)>=Number(x.total||0)&&Number(x.total||0)>0)return "paid";if(paidAmount(x)>0)return "partial";return x.status||"draft"}
function statusLabel(s,o=false){if(o&&s!=="paid"&&s!=="cancelled")return["status-overdue","Dospjelo"];return({draft:["status-draft","Nacrt"],sent:["status-sent","Poslano"],partial:["status-partial","Djelimično plaćeno"],paid:["status-paid","Plaćeno"],cancelled:["status-cancelled","Otkazano"]})[s]||["status-draft","Nacrt"]}
function isOverdue(x){return effectiveStatus(x)!=="paid"&&effectiveStatus(x)!=="cancelled"&&x.dueDate&&new Date(x.dueDate+"T23:59:59")<new Date()}
function openModal(title,body,actions=""){const root=$("modalRoot");root.innerHTML=`<div class="modal-backdrop" id="modalBackdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-close" onclick="closeModal()" aria-label="Zatvori">×</button></div><div class="modal-body">${body}${actions}</div></div></div>`}
function closeModal(){$("modalRoot").innerHTML=""}
function confirmAction(message,yes){openModal("Potvrda",`<p class="confirm-copy">${esc(message)}</p>`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Odustani</button><button class="btn danger" id="confirmYes">Potvrdi</button></div>`);$("confirmYes").onclick=()=>{closeModal();yes()}}
function updateInvoiceBadge(){const e=$("invoiceBadge");if(e)e.textContent=getInvoices().filter(x=>isOverdue(x)).length;updateNotifications?.()}
function saveInvoiceStatus(id,status){const list=getInvoices(),i=list.findIndex(x=>String(x.id)===String(id));if(i<0)return;const x=list[i];if(status==="paid")x.paidAmount=+x.total||0;else if(status!=="partial")x.paidAmount=0;x.status=status;list[i]=x;if(!saveInvoices(list))return;updateInvoiceBadge();toast(status==="paid"?"Faktura je označena kao plaćena.":status==="sent"?"Faktura je označena kao poslana.":"Status fakture je promijenjen.");refreshCurrentView()}
function markInvoicePaid(id){saveInvoiceStatus(id,"paid")}
function markInvoiceSent(id){saveInvoiceStatus(id,"sent")}
function cancelInvoice(id){confirmAction("Označiti ovu fakturu kao otkazanu?",()=>saveInvoiceStatus(id,"cancelled"))}
function recordPaymentModal(id){const x=getInvoices().find(i=>String(i.id)===String(id));if(!x)return;const remaining=Math.max(0,(+x.total||0)-paidAmount(x)),safeId=JSON.stringify(String(x.id));openModal("Evidentiraj uplatu",`<div class="payment-summary"><div><span>Faktura</span><strong>${esc(x.number)}</strong></div><div><span>Ukupno</span><strong>${money(x.total,x.currency)}</strong></div><div><span>Već plaćeno</span><strong>${money(paidAmount(x),x.currency)}</strong></div><div><span>Preostalo</span><strong>${money(remaining,x.currency)}</strong></div></div><div class="grid-2"><div class="field"><label>Iznos uplate</label><input id="payAmount" type="number" min="0" max="${remaining}" step="0.01" value="${remaining}"></div><div class="field"><label>Datum</label><input id="payDate" type="date" value="${today()}"></div><div class="field"><label>Način plaćanja</label><select id="payMethod"><option>Bankovni transfer</option><option>Gotovina</option><option>Kartica</option><option>PayPal</option><option>Ostalo</option></select></div><div class="field"><label>Napomena</label><input id="payNote" placeholder="Opcionalno"></div></div>`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Odustani</button><button class="btn accent" onclick='savePayment(${safeId})'>Sačuvaj uplatu</button></div>`);$("payMethod").value=x.paymentMethod||getSettings().paymentMethod}
function savePayment(id){const list=getInvoices(),i=list.findIndex(x=>String(x.id)===String(id));if(i<0)return;const x=list[i],amount=Math.max(0,+$("payAmount").value||0),remaining=Math.max(0,(+x.total||0)-paidAmount(x));if(!amount||amount>remaining+0.005){toast("Iznos uplate nije ispravan.");return}const method=$("payMethod").value,date=$("payDate").value,note=$("payNote").value.trim();x.paidAmount=Math.min(+x.total||0,paidAmount(x)+amount);x.paymentMethod=method;x.lastPaymentDate=date;x.lastPaymentNote=note;x.payments=Array.isArray(x.payments)?x.payments:[];x.payments.push({amount,date,method,note});x.status=x.paidAmount>=+x.total?"paid":"sent";list[i]=x;if(!saveInvoices(list)){toast("Uplata nije spremljena.");return}closeModal();updateInvoiceBadge();toast(x.status==="paid"?"Faktura je u cijelosti plaćena.":"Uplata je evidentirana.");refreshCurrentView()}
function refreshCurrentView(){const r=location.hash.slice(1)||"dashboard";routes[r]?.()}
function openEntityBulk(type){const config={clients:{title:"klijenti",get:getClients,save:saveClients,label:x=>x.name||"Bez naziva",actions:["delete"]},offers:{title:"ponude",get:getOffers,save:saveOffers,label:x=>`${x.number||"Ponuda"} · ${x.clientName||"Bez klijenta"}`,actions:["sent","accepted","delete"]},catalog:{title:"stavke kataloga",get:getCatalog,save:saveCatalog,label:x=>x.name||"Bez naziva",actions:["active","inactive","delete"]}}[type];if(!config)return;const rows=config.get();if(!rows.length){toast("Nema stavki za odabir.");return}openModal(`Masovne radnje — ${config.title}`,`<p class="page-subtitle">Označite stavke koje želite izmijeniti.</p><div class="bulk-select-list">${rows.map((x,i)=>`<label><input type="checkbox" class="bulk-entity" value="${i}"> <strong>${esc(config.label(x))}</strong></label>`).join("")}</div>`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Odustani</button>${config.actions.includes("sent")?`<button class="btn light" onclick="runEntityBulk('${type}','sent')">Označi poslano</button>`:""}${config.actions.includes("accepted")?`<button class="btn success" onclick="runEntityBulk('${type}','accepted')">Prihvati</button>`:""}${config.actions.includes("active")?`<button class="btn success" onclick="runEntityBulk('${type}','active')">Aktiviraj</button>`:""}${config.actions.includes("inactive")?`<button class="btn light" onclick="runEntityBulk('${type}','inactive')">Deaktiviraj</button>`:""}<button class="btn danger" onclick="runEntityBulk('${type}','delete')">Obriši</button></div>`)}
function runEntityBulk(type,action){const ids=[...document.querySelectorAll('.bulk-entity:checked')].map(x=>+x.value);if(!ids.length){toast("Označite barem jednu stavku.");return}const config={clients:[getClients,saveClients],offers:[getOffers,saveOffers],catalog:[getCatalog,saveCatalog]}[type];if(!config)return;const apply=()=>{let rows=config[0]();if(action==="delete")rows=rows.filter((_,i)=>!ids.includes(i));else rows=rows.map((x,i)=>ids.includes(i)?{...x,...(type==="catalog"?{active:action==="active"}:{status:action})}:x);config[1](rows);closeModal();refreshCurrentView();toast("Masovna radnja je izvršena.")};if(action==='delete')confirmAction(`Brišete ${ids.length} odabranih stavki. Ovu radnju nije moguće opozvati.`,apply);else apply()}
const openEntityBulkBase=openEntityBulk;openEntityBulk=function(type){const config={expenses:{title:'troškovi',key:'expenses',label:item=>`${item.name||'Trošak'} · ${moneyValue(item.amount,item.currency||getSettings().currency)}`},projects:{title:'projekti',key:'projects',label:item=>item.name||'Projekt'},tasks:{title:'zadaci',key:'tasks',label:item=>item.name||'Zadatak'},documents:{title:'prilozi',key:'documents',label:item=>item.name||'Dokument'}}[type];if(!config)return openEntityBulkBase(type);const rows=extGet(config.key);if(!rows.length){toast('Nema stavki za odabir.');return}openModal(`Masovne radnje — ${config.title}`,`<p class="page-subtitle">Označite stavke koje želite obrisati.</p><div class="bulk-select-list">${rows.map((item,index)=>`<label><input type="checkbox" class="bulk-workspace" value="${index}"> <strong>${esc(config.label(item))}</strong></label>`).join('')}</div>`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Odustani</button><button class="btn danger" onclick="runWorkspaceBulk('${type}')">Obriši odabrano</button></div>`)};
function runWorkspaceBulk(type){const config={expenses:'expenses',projects:'projects',tasks:'tasks',documents:'documents'}[type],ids=[...document.querySelectorAll('.bulk-workspace:checked')].map(item=>+item.value);if(!config||!ids.length){toast('Označite barem jednu stavku.');return}confirmAction(`Brišete ${ids.length} odabranih stavki. Ovu radnju nije moguće opozvati.`,()=>{extSet(config,extGet(config).filter((_,index)=>!ids.includes(index)));closeModal();refreshCurrentView();toast('Odabrane stavke su obrisane.')})}
openEntityBulk=function(type){const config={expenses:{title:'troškovi',key:'expenses',label:item=>`${item.name||'Trošak'} · ${moneyValue(item.amount,item.currency||getSettings().currency)}`},projects:{title:'projekti',key:'projects',label:item=>item.name||'Projekt'},tasks:{title:'zadaci',key:'tasks',label:item=>item.name||'Zadatak'},documents:{title:'prilozi',key:'documents',label:item=>item.name||'Dokument'}}[type];if(!config)return openEntityBulkBase(type);const rows=extGet(config.key);if(!rows.length){toast('Nema stavki za odabir.');return}const editor=type==='expenses'?`<div class="field"><label>Nova kategorija</label><input id="bulkWorkspaceValue" placeholder="npr. Softver"></div>`:type==='documents'?`<div class="field"><label>Novi tip priloga</label><select id="bulkWorkspaceValue"><option>Ugovor</option><option>Primljena faktura</option><option>Potvrda</option><option>Ostalo</option></select></div>`:'';const actions=type==='tasks'?`<button class="btn success" onclick="runWorkspaceBulk('${type}','done')">Označi završeno</button><button class="btn light" onclick="runWorkspaceBulk('${type}','open')">Označi otvoreno</button>`:editor?`<button class="btn accent" onclick="runWorkspaceBulk('${type}','update')">Ažuriraj odabrano</button>`:'';openModal(`Masovne radnje — ${config.title}`,`<p class="page-subtitle">Označite stavke, zatim izaberite radnju.</p><div class="bulk-select-list">${rows.map((item,index)=>`<label><input type="checkbox" class="bulk-workspace" value="${index}"> <strong>${esc(config.label(item))}</strong></label>`).join('')}</div>${editor}`,`<div class="modal-actions"><button class="btn light" onclick="closeModal()">Odustani</button>${actions}<button class="btn danger" onclick="runWorkspaceBulk('${type}','delete')">Obriši odabrano</button></div>`)};
function runWorkspaceBulk(type,action='delete'){const key={expenses:'expenses',projects:'projects',tasks:'tasks',documents:'documents'}[type],ids=[...document.querySelectorAll('.bulk-workspace:checked')].map(item=>+item.value);if(!key||!ids.length){toast('Označite barem jednu stavku.');return}const apply=()=>{let rows=extGet(key);if(action==='delete')rows=rows.filter((_,index)=>!ids.includes(index));else if(type==='tasks')rows=rows.map((item,index)=>ids.includes(index)?{...item,done:action==='done'}:item);else if(type==='expenses')rows=rows.map((item,index)=>ids.includes(index)?{...item,category:$('bulkWorkspaceValue').value.trim()}:item);else if(type==='documents')rows=rows.map((item,index)=>ids.includes(index)?{...item,type:$('bulkWorkspaceValue').value}:item);extSet(key,rows);closeModal();refreshCurrentView();toast(action==='delete'?'Odabrane stavke su obrisane.':'Odabrane stavke su ažurirane.')};if(action==='delete')confirmAction(`Brišete ${ids.length} odabranih stavki. Ovu radnju nije moguće opozvati.`,apply);else apply()}
